export const locations = [
  { name: "Afghanistan", code: "AF", phone: "+93" },
  { name: "Albania", code: "AL", phone: "+355" },
  { name: "Algeria", code: "DZ", phone: "+213" },
  { name: "Andorra", code: "AD", phone: "+376" },
  { name: "Angola", code: "AO", phone: "+244" },
  { name: "Antigua and Barbuda", code: "AG", phone: "+1-268" },
  { name: "Argentina", code: "AR", phone: "+54" },
  { name: "Armenia", code: "AM", phone: "+374" },
  { name: "Australia", code: "AU", phone: "+61" },
  { name: "Austria", code: "AT", phone: "+43" },
  { name: "Azerbaijan", code: "AZ", phone: "+994" },
  { name: "Bahamas", code: "BS", phone: "+1-242" },
  { name: "Bahrain", code: "BH", phone: "+973" },
  { name: "Bangladesh", code: "BD", phone: "+880" },
  { name: "Barbados", code: "BB", phone: "+1-246" },
  { name: "Belarus", code: "BY", phone: "+375" },
  { name: "Belgium", code: "BE", phone: "+32" },
  { name: "Belize", code: "BZ", phone: "+501" },
  { name: "Benin", code: "BJ", phone: "+229" },
  { name: "Bhutan", code: "BT", phone: "+975" },
  { name: "Bolivia", code: "BO", phone: "+591" },
  { name: "Bosnia and Herzegovina", code: "BA", phone: "+387" },
  { name: "Botswana", code: "BW", phone: "+267" },
  { name: "Brazil", code: "BR", phone: "+55" },
  { name: "Brunei", code: "BN", phone: "+673" },
  { name: "Bulgaria", code: "BG", phone: "+359" },
  { name: "Burkina Faso", code: "BF", phone: "+226" },
  { name: "Burundi", code: "BI", phone: "+257" },
  { name: "Cabo Verde", code: "CV", phone: "+238" },
  { name: "Cambodia", code: "KH", phone: "+855" },
  { name: "Cameroon", code: "CM", phone: "+237" },
  { name: "Canada", code: "CA", phone: "+1" },
  { name: "Central African Republic", code: "CF", phone: "+236" },
  { name: "Chad", code: "TD", phone: "+235" },
  { name: "Chile", code: "CL", phone: "+56" },
  { name: "China", code: "CN", phone: "+86" },
  { name: "Colombia", code: "CO", phone: "+57" },
  { name: "Comoros", code: "KM", phone: "+269" },
  { name: "Congo", code: "CG", phone: "+242" },
  { name: "Costa Rica", code: "CR", phone: "+506" },
  { name: "Croatia", code: "HR", phone: "+385" },
  { name: "Cuba", code: "CU", phone: "+53" },
  { name: "Cyprus", code: "CY", phone: "+357" },
  { name: "Czech Republic", code: "CZ", phone: "+420" },
  { name: "Denmark", code: "DK", phone: "+45" },
  { name: "Djibouti", code: "DJ", phone: "+253" },
  { name: "Dominica", code: "DM", phone: "+1-767" },
  { name: "Dominican Republic", code: "DO", phone: "+1-809, +1-829, +1-849" },
  { name: "Ecuador", code: "EC", phone: "+593" },
  { name: "Egypt", code: "EG", phone: "+20" },
  { name: "El Salvador", code: "SV", phone: "+503" },
  { name: "Equatorial Guinea", code: "GQ", phone: "+240" },
  { name: "Eritrea", code: "ER", phone: "+291" },
  { name: "Estonia", code: "EE", phone: "+372" },
  { name: "Eswatini", code: "SZ", phone: "+268" },
  { name: "Ethiopia", code: "ET", phone: "+251" },
  { name: "Fiji", code: "FJ", phone: "+679" },
  { name: "Finland", code: "FI", phone: "+358" },
  { name: "France", code: "FR", phone: "+33" },
  { name: "Gabon", code: "GA", phone: "+241" },
  { name: "Gambia", code: "GM", phone: "+220" },
  { name: "Georgia", code: "GE", phone: "+995" },
  { name: "Germany", code: "DE", phone: "+49" },
  { name: "Ghana", code: "GH", phone: "+233" },
  { name: "Greece", code: "GR", phone: "+30" },
  { name: "Grenada", code: "GD", phone: "+1-473" },
  { name: "Guatemala", code: "GT", phone: "+502" },
  { name: "Guinea", code: "GN", phone: "+224" },
  { name: "Guinea-Bissau", code: "GW", phone: "+245" },
  { name: "Guyana", code: "GY", phone: "+592" },
  { name: "Haiti", code: "HT", phone: "+509" },
  { name: "Honduras", code: "HN", phone: "+504" },
  { name: "Hungary", code: "HU", phone: "+36" },
  { name: "Iceland", code: "IS", phone: "+354" },
  { name: "India", code: "IN", phone: "+91" },
  { name: "Indonesia", code: "ID", phone: "+62" },
  { name: "Iran", code: "IR", phone: "+98" },
  { name: "Iraq", code: "IQ", phone: "+964" },
  { name: "Ireland", code: "IE", phone: "+353" },
  { name: "Israel", code: "IL", phone: "+972" },
  { name: "Italy", code: "IT", phone: "+39" },
  { name: "Jamaica", code: "JM", phone: "+1-876" },
  { name: "Japan", code: "JP", phone: "+81" },
  { name: "Jordan", code: "JO", phone: "+962" },
  { name: "Kazakhstan", code: "KZ", phone: "+7" },
  { name: "Kenya", code: "KE", phone: "+254" },
  { name: "Kiribati", code: "KI", phone: "+686" },
  { name: "Korea, North", code: "KP", phone: "+850" },
  { name: "Korea, South", code: "KR", phone: "+82" },
  { name: "Kosovo", code: "XK", phone: "+383" },
  { name: "Kuwait", code: "KW", phone: "+965" },
  { name: "Kyrgyzstan", code: "KG", phone: "+996" },
  { name: "Laos", code: "LA", phone: "+856" },
  { name: "Latvia", code: "LV", phone: "+371" },
  { name: "Lebanon", code: "LB", phone: "+961" },
  { name: "Lesotho", code: "LS", phone: "+266" },
  { name: "Liberia", code: "LR", phone: "+231" },
  { name: "Libya", code: "LY", phone: "+218" },
  { name: "Liechtenstein", code: "LI", phone: "+423" },
  { name: "Lithuania", code: "LT", phone: "+370" },
  { name: "Luxembourg", code: "LU", phone: "+352" },
  { name: "Madagascar", code: "MG", phone: "+261" },
  { name: "Malawi", code: "MW", phone: "+265" },
  { name: "Malaysia", code: "MY", phone: "+60" },
  { name: "Maldives", code: "MV", phone: "+960" },
  { name: "Mali", code: "ML", phone: "+223" },
  { name: "Malta", code: "MT", phone: "+356" },
  { name: "Marshall Islands", code: "MH", phone: "+692" },
  { name: "Mauritania", code: "MR", phone: "+222" },
  { name: "Mauritius", code: "MU", phone: "+230" },
  { name: "Mexico", code: "MX", phone: "+52" },
  { name: "Micronesia", code: "FM", phone: "+691" },
  { name: "Moldova", code: "MD", phone: "+373" },
  { name: "Monaco", code: "MC", phone: "+377" },
  { name: "Mongolia", code: "MN", phone: "+976" },
  { name: "Montenegro", code: "ME", phone: "+382" },
  { name: "Morocco", code: "MA", phone: "+212" },
  { name: "Mozambique", code: "MZ", phone: "+258" },
  { name: "Myanmar", code: "MM", phone: "+95" },
  { name: "Namibia", code: "NA", phone: "+264" },
  { name: "Nauru", code: "NR", phone: "+674" },
  { name: "Nepal", code: "NP", phone: "+977" },
  { name: "Netherlands", code: "NL", phone: "+31" },
  { name: "New Zealand", code: "NZ", phone: "+64" },
  { name: "Nicaragua", code: "NI", phone: "+505" },
  { name: "Niger", code: "NE", phone: "+227" },
  { name: "Nigeria", code: "NG", phone: "+234" },
  { name: "North Macedonia", code: "MK", phone: "+389" },
  { name: "Norway", code: "NO", phone: "+47" },
  { name: "Oman", code: "OM", phone: "+968" },
  { name: "Pakistan", code: "PK", phone: "+92" },
  { name: "Palau", code: "PW", phone: "+680" },
  { name: "Panama", code: "PA", phone: "+507" },
  { name: "Papua New Guinea", code: "PG", phone: "+675" },
  { name: "Paraguay", code: "PY", phone: "+595" },
  { name: "Peru", code: "PE", phone: "+51" },
  { name: "Philippines", code: "PH", phone: "+63" },
  { name: "Poland", code: "PL", phone: "+48" },
  { name: "Portugal", code: "PT", phone: "+351" },
  { name: "Qatar", code: "QA", phone: "+974" },
  { name: "Romania", code: "RO", phone: "+40" },
  { name: "Russia", code: "RU", phone: "+7" },
  { name: "Rwanda", code: "RW", phone: "+250" },
  { name: "Saint Kitts and Nevis", code: "KN", phone: "+1-869" },
  { name: "Saint Lucia", code: "LC", phone: "+1-758" },
  { name: "Saint Vincent and the Grenadines", code: "VC", phone: "+1-784" },
  { name: "Samoa", code: "WS", phone: "+685" },
  { name: "San Marino", code: "SM", phone: "+378" },
  { name: "Sao Tome and Principe", code: "ST", phone: "+239" },
  { name: "Saudi Arabia", code: "SA", phone: "+966" },
  { name: "Senegal", code: "SN", phone: "+221" },
  { name: "Serbia", code: "RS", phone: "+381" },
  { name: "Seychelles", code: "SC", phone: "+248" },
  { name: "Sierra Leone", code: "SL", phone: "+232" },
  { name: "Singapore", code: "SG", phone: "+65" },
  { name: "Slovakia", code: "SK", phone: "+421" },
  { name: "Slovenia", code: "SI", phone: "+386" },
  { name: "Solomon Islands", code: "SB", phone: "+677" },
  { name: "Somalia", code: "SO", phone: "+252" },
  { name: "South Africa", code: "ZA", phone: "+27" },
  { name: "South Sudan", code: "SS", phone: "+211" },
  { name: "Spain", code: "ES", phone: "+34" },
  { name: "Sri Lanka", code: "LK", phone: "+94" },
  { name: "Sudan", code: "SD", phone: "+249" },
  { name: "Suriname", code: "SR", phone: "+597" },
  { name: "Sweden", code: "SE", phone: "+46" },
  { name: "Switzerland", code: "CH", phone: "+41" },
  { name: "Syria", code: "SY", phone: "+963" },
  { name: "Taiwan", code: "TW", phone: "+886" },
  { name: "Tajikistan", code: "TJ", phone: "+992" },
  { name: "Tanzania", code: "TZ", phone: "+255" },
  { name: "Thailand", code: "TH", phone: "+66" },
  { name: "Togo", code: "TG", phone: "+228" },
  { name: "Tonga", code: "TO", phone: "+676" },
  { name: "Trinidad and Tobago", code: "TT", phone: "+1-868" },
  { name: "Tunisia", code: "TN", phone: "+216" },
  { name: "Turkey", code: "TR", phone: "+90" },
  { name: "Turkmenistan", code: "TM", phone: "+993" },
  { name: "Tuvalu", code: "TV", phone: "+688" },
  { name: "Uganda", code: "UG", phone: "+256" },
  { name: "Ukraine", code: "UA", phone: "+380" },
  { name: "United Arab Emirates", code: "AE", phone: "+971" },
  { name: "United Kingdom", code: "GB", phone: "+44" },
  { name: "United States", code: "US", phone: "+1" },
  { name: "Uruguay", code: "UY", phone: "+598" },
  { name: "Uzbekistan", code: "UZ", phone: "+998" },
  { name: "Vanuatu", code: "VU", phone: "+678" },
  { name: "Vatican City", code: "VA", phone: "+379" },
  { name: "Venezuela", code: "VE", phone: "+58" },
  { name: "Vietnam", code: "VN", phone: "+84" },
  { name: "Yemen", code: "YE", phone: "+967" },
  { name: "Zambia", code: "ZM", phone: "+260" },
  { name: "Zimbabwe", code: "ZW", phone: "+263" },
  { name: "Asia" },
  { name: "Tokyo" },
  { name: "Delhi" },
  { name: "Shanghai" },
  { name: "Mumbai" },
  { name: "Beijing" },
  { name: "Osaka" },
  { name: "Karachi" },
  { name: "Dhaka" },
  { name: "Bangkok" },
  { name: "Istanbul" },
  { name: "Manila" },
  { name: "Seoul" },
  { name: "Jakarta" },
  { name: "Lahore" },
  { name: "Shenzhen" },
  { name: "Chennai" },
  { name: "Bangalore" },
  { name: "Ho Chi Minh City" },
  { name: "Hong Kong" },
  { name: "Africa" },
  { name: "Lagos" },
  { name: "Cairo" },
  { name: "Kinshasa" },
  { name: "Johannesburg" },
  { name: "Nairobi" },
  { name: "Casablanca" },
  { name: "Abidjan" },
  { name: "Alexandria" },
  { name: "Addis Ababa" },
  { name: "Accra" },
  { name: "Dar es Salaam" },
  { name: "Khartoum" },
  { name: "Durban" },
  { name: "Luanda" },
  { name: "Tripoli" },
  { name: "Dakar" },
  { name: "Algiers" },
  { name: "North America" },
  { name: "Mexico City" },
  { name: "New York" },
  { name: "Los Angeles" },
  { name: "Chicago" },
  { name: "Toronto" },
  { name: "Houston" },
  { name: "Montreal" },
  { name: "Philadelphia" },
  { name: "Phoenix" },
  { name: "San Antonio" },
  { name: "San Diego" },
  { name: "Dallas" },
  { name: "San Jose" },
  { name: "Austin" },
  { name: "Jacksonville" },
  { name: "San Francisco" },
  { name: "Columbus" },
  { name: "Charlotte" },
  { name: "Indianapolis" },
  { name: "Seattle" },
  { name: "Denver" },
  { name: "Washington" },
  { name: "Boston" },
  { name: "El Paso" },
  { name: "Detroit" },
  { name: "Nashville" },
  { name: "Portland" },
  { name: "Memphis" },
  { name: "Oklahoma City" },
  { name: "Las Vegas" },
  { name: "Louisville" },
  { name: "Baltimore" },
  { name: "Milwaukee" },
  { name: "Albuquerque" },
  { name: "Tucson" },
  { name: "Fresno" },
  { name: "Sacramento" },
  { name: "Kansas City" },
  { name: "Long Beach" },
  { name: "Mesa" },
  { name: "Atlanta" },
  { name: "Colorado Springs" },
  { name: "Virginia Beach" },
  { name: "Raleigh" },
  { name: "Omaha" },
  { name: "Miami" },
  { name: "Oakland" },
  { name: "Minneapolis" },
  { name: "Tulsa" },
  { name: "Wichita" },
  { name: "New Orleans" },
  { name: "Arlington" },
  { name: "Cleveland" },
  { name: "Bakersfield" },
  { name: "Tampa" },
  { name: "Aurora" },
  { name: "Honolulu" },
  { name: "Anaheim" },
  { name: "Santa Ana" },
  { name: "Corpus Christi" },
  { name: "Riverside" },
  { name: "St. Louis" },
  { name: "Lexington" },
  { name: "Pittsburgh" },
  { name: "Stockton" },
  { name: "Anchorage" },
  { name: "Cincinnati" },
  { name: "Saint Paul" },
  { name: "Toledo" },
  { name: "Newark" },
  { name: "Greensboro" },
  { name: "Plano" },
  { name: "Henderson" },
  { name: "Lincoln" },
  { name: "Buffalo" },
  { name: "Fort Wayne" },
  { name: "Jersey City" },
  { name: "Chula Vista" },
  { name: "Orlando" },
  { name: "St. Petersburg" },
  { name: "Chandler" },
  { name: "Laredo" },
  { name: "Norfolk" },
  { name: "Durham" },
  { name: "Madison" },
  { name: "Lubbock" },
  { name: "Irvine" },
  { name: "Winston-Salem" },
  { name: "Glendale" },
  { name: "Garland" },
  { name: "Hialeah" },
  { name: "Reno" },
  { name: "Chesapeake" },
  { name: "Gilbert" },
  { name: "Baton Rouge" },
  { name: "Irving" },
  { name: "Scottsdale" },
  { name: "North Las Vegas" },
  { name: "Fremont" },
  { name: "Boise" },
  { name: "Richmond" },
  { name: "San Bernardino" },
  { name: "Birmingham" },
  { name: "Spokane" },
  { name: "Rochester" },
  { name: "Des Moines" },
  { name: "Modesto" },
  { name: "Fayetteville" },
  { name: "Tacoma" },
  { name: "Oxnard" },
  { name: "Fontana" },
  { name: "Columbus" },
  { name: "Montgomery" },
  { name: "Moreno Valley" },
  { name: "Shreveport" },
  { name: "Aurora" },
  { name: "Yonkers" },
  { name: "Akron" },
  { name: "Huntington Beach" },
  { name: "Little Rock" },
  { name: "Augusta" },
  { name: "Amarillo" },
  { name: "Glendale" },
  { name: "Mobile" },
  { name: "Grand Rapids" },
  { name: "Salt Lake City" },
  { name: "Tallahassee" },
  { name: "Huntsville" },
  { name: "Grand Prairie" },
  { name: "Knoxville" },
  { name: "Worcester" },
  { name: "Newport News" },
  { name: "Brownsville" },
  { name: "Overland Park" },
  { name: "Santa Clarita" },
  { name: "Providence" },
  { name: "Garden Grove" },
  { name: "Chattanooga" },
  { name: "Oceanside" },
  { name: "Jackson" },
  { name: "Fort Lauderdale" },
  { name: "Santa Rosa" },
  { name: "Rancho Cucamonga" },
  { name: "Port St. Lucie" },
  { name: "Tempe" },
  { name: "Ontario" },
  { name: "Vancouver" },
  { name: "Cape Coral" },
  { name: "Sioux Falls" },
  { name: "Springfield" },
  { name: "Peoria" },
  { name: "Pembroke Pines" },
  { name: "Elk Grove" },
  { name: "Salem" },
  { name: "Lancaster" },
  { name: "Corona" },
  { name: "Eugene" },
  { name: "Palmdale" },
  { name: "Salinas" },
  { name: "Springfield" },
  { name: "Pasadena" },
  { name: "Fort Collins" },
  { name: "Hayward" },
  { name: "Pomona" },
  { name: "Cary" },
  { name: "Rockford" },
  { name: "Alexandria" },
  { name: "Escondido" },
  { name: "McKinney" },
  { name: "Kansas City" },
  { name: "Joliet" },
  { name: "Sunnyvale" },
  { name: "Torrance" },
  { name: "Bridgeport" },
  { name: "Lakewood" },
  { name: "Hollywood" },
  { name: "Paterson" },
  { name: "Naperville" },
  { name: "Syracuse" },
  { name: "Mesquite" },
  { name: "Dayton" },
  { name: "Savannah" },
  { name: "Clarksville" },
  { name: "Orange" },
  { name: "Pasadena" },
  { name: "Fullerton" },
  { name: "Killeen" },
  { name: "Frisco" },
  { name: "Hampton" },
  { name: "McAllen" },
  { name: "Warren" },
  { name: "Bellevue" },
  { name: "West Valley City" },
  { name: "Columbia" },
  { name: "Olathe" },
  { name: "Sterling Heights" },
  { name: "New Haven" },
  { name: "Miramar" },
  { name: "Waco" },
  { name: "Thousand Oaks" },
  { name: "Cedar Rapids" },
  { name: "Charleston" },
  { name: "Visalia" },
  { name: "Topeka" },
  { name: "Elizabeth" },
  { name: "Gainesville" },
  { name: "Thornton" },
  { name: "Roseville" },
  { name: "Carrollton" },
  { name: "Coral Springs" },
  { name: "Stamford" },
  { name: "Simi Valley" },
  { name: "Concord" },
  { name: "Hartford" },
  { name: "Kent" },
  { name: "Lafayette" },
  { name: "Midland" },
  { name: "Surprise" },
  { name: "Denton" },
  { name: "Victorville" },
  { name: "Evansville" },
  { name: "Santa Clara" },
  { name: "Abilene" },
  { name: "Athens" },
  { name: "Vallejo" },
  { name: "Allentown" },
  { name: "Norman" },
  { name: "Beaumont" },
  { name: "Independence" },
  { name: "Murfreesboro" },
  { name: "Ann Arbor" },
  { name: "Springfield" },
  { name: "Berkeley" },
  { name: "Peoria" },
  { name: "Provo" },
  { name: "El Monte" },
  { name: "Columbia" },
  { name: "Lansing" },
  { name: "Fargo" },
  { name: "Downey" },
  { name: "Costa Mesa" },
  { name: "Wilmington" },
  { name: "Arvada" },
  { name: "Inglewood" },
  { name: "Miami Gardens" },
  { name: "Carlsbad" },
  { name: "Westminster" },
  { name: "Rochester" },
  { name: "Odessa" },
  { name: "Manchester" },
  { name: "Elgin" },
  { name: "West Jordan" },
  { name: "Round Rock" },
  { name: "Clearwater" },
  { name: "Waterbury" },
  { name: "Gresham" },
  { name: "Fairfield" },
  { name: "Billings" },
  { name: "Lowell" },
  { name: "San Buenaventura" },
  { name: "Pueblo" },
  { name: "High Point" },
  { name: "West Covina" },
  { name: "Richmond" },
  { name: "Murrieta" },
  { name: "Cambridge" },
  { name: "Antioch" },
  { name: "Temecula" },
  { name: "Norwalk" },
  { name: "Centennial" },
  { name: "Everett" },
  { name: "Palm Bay" },
  { name: "Wichita Falls" },
  { name: "Green Bay" },
  { name: "Daly City" },
  { name: "Burbank" },
  { name: "Richardson" },
  { name: "Pompano Beach" },
  { name: "North Charleston" },
  { name: "Broken Arrow" },
  { name: "Boulder" },
  { name: "West Palm Beach" },
  { name: "Santa Maria" },
  { name: "El Cajon" },
  { name: "Davenport" },
  { name: "Rialto" },
  { name: "Las Cruces" },
  { name: "San Mateo" },
  { name: "Lewisville" },
  { name: "South Bend" },
  { name: "Lakeland" },
  { name: "Erie" },
  { name: "Tyler" },
  { name: "Pearland" },
  { name: "College Station" },
  { name: "Kenosha" },
  { name: "Sandy Springs" },
  { name: "Clovis" },
  { name: "Flint" },
  { name: "Roanoke" },
  { name: "Albany" },
  { name: "Jurupa Valley" },
  { name: "Compton" },
  { name: "San Angelo" },
  { name: "Hillsboro" },
  { name: "Lawton" },
  { name: "Renton" },
  { name: "Vista" },
  { name: "Davie" },
  { name: "Greeley" },
  { name: "Mission Viejo" },
  { name: "Portsmouth" },
  { name: "Dearborn" },
  { name: "South Gate" },
  { name: "Tuscaloosa" },
  { name: "Livonia" },
  { name: "New Bedford" },
  { name: "Vacaville" },
  { name: "Brockton" },
  { name: "Roswell" },
  { name: "Beaverton" },
  { name: "Quincy" },
  { name: "Sparks" },
  { name: "Yakima" },
  { name: "Lee's Summit" },
  { name: "Federal Way" },
  { name: "Carson" },
  { name: "Santa Monica" },
  { name: "Hesperia" },
  { name: "Allen" },
  { name: "Rio Rancho" },
  { name: "Yuma" },
  { name: "Westminster" },
  { name: "Orem" },
  { name: "Lynn" },
  { name: "Redding" },
  { name: "Spokane Valley" },
  { name: "Miami Beach" },
  { name: "League City" },
  { name: "Lawrence" },
  { name: "Santa Barbara" },
  { name: "Plantation" },
  { name: "Sandy" },
  { name: "Sunrise" },
  { name: "Macon" },
  { name: "Longmont" },
  { name: "Boca Raton" },
  { name: "San Marcos" },
  { name: "Greenville" },
  { name: "Waukegan" },
  { name: "Fall River" },
  { name: "Chico" },
  { name: "Newton" },
  { name: "San Leandro" },
  { name: "Reading" },
  { name: "Fort Smith" },
  { name: "Norwalk" },
  { name: "Albany" },
  { name: "Bloomington" },
  { name: "Tracy" },
  { name: "Irvine" },
  { name: "Whittier" },
  { name: "Nampa" },
  { name: "Gary" },
  { name: "Berwyn" },
  { name: "Redwood City" },
  { name: "Yonkers" },
  { name: "Spokane" },
  { name: "Renton" },
  { name: "Hemet" },
  { name: "South Lyon" },
  { name: "Turlock" },
  { name: "Lake Forest" },
  { name: "Napa" },
  { name: "Olympia" },
  { name: "Edinburg" },
  { name: "Troy" },
  { name: "Madera" },
  { name: "Joplin" },
  { name: "Chino" },
  { name: "Haverhill" },
  { name: "Newport Beach" },
  { name: "Rancho Cordova" },
  { name: "San Ramon" },
  { name: "Bellingham" },
  { name: "Bloomington" },
  { name: "Buena Park" },
  { name: "Tamarac" },
  { name: "Arlington Heights" },
  { name: "Warwick" },
  { name: "Parma" },
  { name: "Loveland" },
  { name: "Boynton Beach" },
  { name: "Layton" },
  { name: "Missouri City" },
  { name: "Riverview" },
  { name: "South Fulton" },
  { name: "Mishawaka" },
  { name: "Largo" },
  { name: "St. Joseph" },
  { name: "Pawtucket" },
  { name: "Lauderhill" },
  { name: "St. George" },
  { name: "Framingham" },
  { name: "Alhambra" },
  { name: "Utica" },
  { name: "Manteca" },
  { name: "Muncie" },
  { name: "Mountain View" },
  { name: "Cicero" },
  { name: "Medford" },
  { name: "Baldwin Park" },
  { name: "Deerfield Beach" },
  { name: "Bossier City" },
  { name: "Rock Hill" },
  { name: "Melbourne" },
  { name: "St. Cloud" },
  { name: "Kokomo" },
  { name: "Davis" },
  { name: "South Bend" },
  { name: "South San Francisco" },
  { name: "Folsom" },
  { name: "Pine Hills" },
  { name: "Pleasanton" },
  { name: "Terre Haute" },
  { name: "Smyrna" },
  { name: "Conway" },
  { name: "Baytown" },
  { name: "Wyoming" },
  { name: "Perris" },
  { name: "Highlands Ranch" },
  { name: "Westland" },
  { name: "Auburn" },
  { name: "Cranston" },
  { name: "Santa Fe" },
  { name: "New Braunfels" },
  { name: "Passaic" },
  { name: "Mansfield" },
  { name: "Hattiesburg" },
  { name: "East Los Angeles" },
  { name: "Cuyahoga Falls" },
  { name: "Dothan" },
  { name: "Santa Cruz" },
  { name: "Fishers" },
  { name: "Danbury" },
  { name: "Concord" },
  { name: "Dearborn Heights" },
  { name: "Redlands" },
  { name: "Schaumburg" },
  { name: "Livermore" },
  { name: "South Gate" },
  { name: "San Clemente" },
  { name: "West Sacramento" },
  { name: "Kirkland" },
  { name: "Edmond" },
  { name: "Rowlett" },
  { name: "Burnsville" },
  { name: "O'Fallon" },
  { name: "Rapid City" },
  { name: "Hoffman Estates" },
  { name: "Yorba Linda" },
  { name: "Union City" },
  { name: "Upland" },
  { name: "Lynwood" },
  { name: "Apple Valley" },
  { name: "Redmond" },
  { name: "Kenner" },
  { name: "Mansfield" },
  { name: "Laguna Niguel" },
  { name: "Pocatello" },
  { name: "Lodi" },
  { name: "La Habra" },
  { name: "Lorain" },
  { name: "Milpitas" },
  { name: "Petaluma" },
  { name: "Pinellas Park" },
  { name: "Tigard" },
  { name: "Eau Claire" },
  { name: "North Richland Hills" },
  { name: "North Little Rock" },
  { name: "Broomfield" },
  { name: "Walnut Creek" },
  { name: "Chino Hills" },
  { name: "Everett" },
  { name: "Rancho Santa Margarita" },
  { name: "Sanford" },
  { name: "Wesley Chapel" },
  { name: "Woodbury" },
  { name: "Coachella" },
  { name: "Euless" },
  { name: "Hoboken" },
  { name: "Lake Charles" },
  { name: "Pflugerville" },
  { name: "Alameda" },
  { name: "Bellevue" },
  { name: "Bellflower" },
  { name: "Tustin" },
  { name: "South Jordan" },
  { name: "Meridian" },
  { name: "La Mesa" },
  { name: "Burlington" },
  { name: "Saginaw" },
  { name: "Flower Mound" },
  { name: "Mount Pleasant" },
  { name: "Lancaster" },
  { name: "Georgetown" },
  { name: "Youngstown" },
  { name: "Palo Alto" },
  { name: "West New York" },
  { name: "Auburn" },
  { name: "North Miami" },
  { name: "Camarillo" },
  { name: "Shawnee" },
  { name: "Pasco" },
  { name: "Rockville" },
  { name: "Southfield" },
  { name: "Dublin" },
  { name: "Casper" },
  { name: "Pensacola" },
  { name: "Hammond" },
  { name: "Corvallis" },
  { name: "Diamond Bar" },
  { name: "Bowling Green" },
  { name: "Port Orange" },
  { name: "Novi" },
  { name: "San Luis Obispo" },
  { name: "Marysville" },
  { name: "Lakewood" },
  { name: "Cheyenne" },
  { name: "Perth Amboy" },
  { name: "Coon Rapids" },
  { name: "Watsonville" },
  { name: "Parker" },
  { name: "Taylorsville" },
  { name: "Palm Coast" },
  { name: "Montebello" },
  { name: "South San Francisco" },
  { name: "West Allis" },
  { name: "Draper" },
  { name: "Encinitas" },
  { name: "Eagan" },
  { name: "East Orange" },
  { name: "Port Arthur" },
  { name: "North Port" },
  { name: "Oshkosh" },
  { name: "Mansfield" },
  { name: "Lake Havasu City" },
  { name: "Glen Burnie" },
  { name: "Buckeye" },
  { name: "The Colony" },
  { name: "Bismarck" },
  { name: "Normal" },
  { name: "Peabody" },
  { name: "Keller" },
  { name: "South Hill" },
  { name: "Bloomington" },
  { name: "Elkhart" },
  { name: "Great Falls" },
  { name: "Wheaton" },
  { name: "Huntington Park" },
  { name: "Addison" },
  { name: "Oak Park" },
  { name: "Florissant" },
  { name: "Danville" },
  { name: "Niagara Falls" },
  { name: "Moline" },
  { name: "Lompoc" },
  { name: "Pico Rivera" },
  { name: "Newark" },
  { name: "Pittsfield" },
  { name: "Wilson" },
  { name: "Mankato" },
  { name: "Palm Desert" },
  { name: "Rocklin" },
  { name: "Palm Springs" },
  { name: "Castle Rock" },
  { name: "Alpharetta" },
  { name: "Port Charlotte" },
  { name: "Twin Falls" },
  { name: "Jeffersonville" },
  { name: "Waldorf" },
  { name: "Pottstown" },
  { name: "Palm Beach Gardens" },
  { name: "Minnetonka" },
  { name: "West Haven" },
  { name: "DeKalb" },
  { name: "Grapevine" },
  { name: "St. Charles" },
  { name: "Sheboygan" },
  { name: "Maricopa" },
  { name: "Kendale Lakes" },
  { name: "Northglenn" },
  { name: "Fond du Lac" },
  { name: "Hilton Head Island" },
  { name: "Carol Stream" },
  { name: "Hanford" },
  { name: "Eden Prairie" },
  { name: "Monterey Park" },
  { name: "Chesterfield" },
  { name: "Margate" },
  { name: "Covina" },
  { name: "Winchester" },
  { name: "Huntersville" },
  { name: "Saratoga Springs" },
  { name: "Woonsocket" },
  { name: "Bel Air South" },
  { name: "Wausau" },
  { name: "Marlborough" },
  { name: "Glenview" },
  { name: "Lehi" },
  { name: "Collierville" },
  { name: "West Des Moines" },
  { name: "Kingsport" },
  { name: "Cedar Park" },
  { name: "Summerville" },
  { name: "Titusville" },
  { name: "Dunedin" },
  { name: "North Providence" },
  { name: "Maple Grove" },
  { name: "Decatur" },
  { name: "Oak Lawn" },
  { name: "San Bruno" },
  { name: "Bartlett" },
  { name: "Bradenton" },
  { name: "Pontiac" },
  { name: "St. Clair Shores" },
  { name: "Apache Junction" },
  { name: "Middletown" },
  { name: "Stillwater" },
  { name: "Elmhurst" },
  { name: "Mentor" },
  { name: "Cottonwood Heights" },
  { name: "Eastvale" },
  { name: "Cleveland Heights" },
  { name: "North Ridgeville" },
  { name: "Brentwood" },
  { name: "Crystal Lake" },
  { name: "Roseburg" },
  { name: "Bozeman" },
  { name: "Burien" },
  { name: "Marana" },
  { name: "Coon Rapids" },
  { name: "La Crosse" },
  { name: "Kettering" },
  { name: "New Berlin" },
  { name: "Murray" },
  { name: "Moorhead" },
  { name: "Cypress" },
  { name: "East Lansing" },
  { name: "Rosemead" },
  { name: "Duncanville" },
  { name: "St. Louis Park" },
  { name: "Gaithersburg" },
  { name: "Winter Garden" },
  { name: "Rocky Mount" },
  { name: "Commerce City" },
  { name: "Portage" },
  { name: "Des Plaines" },
  { name: "Plainfield" },
  { name: "Mount Vernon" },
  { name: "Cleveland" },
  { name: "Clifton" },
  { name: "Cerritos" },
  { name: "New Rochelle" },
  { name: "Lakeville" },
  { name: "La Puente" },
  { name: "Orland Park" },
  { name: "Tucker" },
  { name: "Oakland Park" },
  { name: "West Lafayette" },
  { name: "Hazelwood" },
  { name: "Berkeley" },
  { name: "Lima" },
  { name: "Elyria" },
  { name: "Broomfield" },
  { name: "Smyrna" },
  { name: "Santee" },
  { name: "Westerville" },
  { name: "Carolyn" },
  { name: "Haltom City" },
  { name: "White Plains" },
  { name: "Davis" },
  { name: "Palm Harbor" },
  { name: "Port Huron" },
  { name: "Woodland" },
  { name: "Redondo Beach" },
  { name: "Mount Prospect" },
  { name: "Hanover Park" },
  { name: "Calexico" },
  { name: "Park Ridge" },
  { name: "Midwest City" },
  { name: "University Place" },
  { name: "Bristol" },
  { name: "Marion" },
  { name: "Doral" },
  { name: "San Gabriel" },
  { name: "Kennewick" },
  { name: "Millcreek" },
  { name: "East Providence" },
  { name: "Meadow Woods" },
  { name: "Medford" },
  { name: "Bentonville" },
  { name: "Coppell" },
  { name: "Phenix City" },
  { name: "Huntsville" },
  { name: "Dover" },
  { name: "Peachtree Corners" },
  { name: "Herriman" },
  { name: "Lake Elsinore" },
  { name: "Queen Creek" },
  { name: "Glen Allen" },
  { name: "Fountain Valley" },
  { name: "Mishawaka" },
  { name: "Rome" },
  { name: "La Mirada" },
  { name: "Lenexa" },
  { name: "Kannapolis" },
  { name: "Pittsburg" },
  { name: "Attleboro" },
  { name: "Bullhead City" },
  { name: "Hackensack" },
  { name: "Linden" },
  { name: "Cedar Hill" },
  { name: "Campbell" },
  { name: "Annapolis" },
  { name: "Tooele" },
  { name: "Manassas" },
  { name: "Waterloo" },
  { name: "La Quinta" },
  { name: "Morgan Hill" },
  { name: "Rancho Palos Verdes" },
  { name: "Palm Beach Gardens" },
  { name: "West Seneca" },
  { name: "Burlington" },
  { name: "Apex" },
  { name: "Muskogee" },
  { name: "Owensboro" },
  { name: "North Lauderdale" },
  { name: "Shelton" },
  { name: "Edina" },
  { name: "Covina" },
  { name: "Hopkinsville" },
  { name: "Maplewood" },
  { name: "Romeoville" },
  { name: "Duncan" },
  { name: "Atlantic City" },
  { name: "Clermont" },
  { name: "West Chicago" },
  { name: "Florin" },
  { name: "Franklin" },
  { name: "Roy" },
  { name: "Winter Haven" },
  { name: "Chelsea" },
  { name: "Valley Stream" },
  { name: "Bartlesville" },
  { name: "Grove City" },
  { name: "Plant City" },
  { name: "Greenville" },
  { name: "Sierra Vista" },
  { name: "Ames" },
  { name: "West Orange" },
  { name: "Cedar City" },
  { name: "Coral Gables" },
  { name: "Starkville" },
  { name: "Pine Bluff" },
  { name: "Peekskill" },
  { name: "West Fargo" },
  { name: "Lewiston" },
  { name: "Huber Heights" },
  { name: "Cleveland" },
  { name: "North Olmsted" },
  { name: "Cutler Bay" },
  { name: "Mansfield" },
  { name: "Hurst" },
  { name: "West Whittier-Los Nietos" },
  { name: "Findlay" },
  { name: "Clifton Park" },
  { name: "Palm City" },
  { name: "North Tonawanda" },
  { name: "Fairbanks" },
  { name: "Placentia" },
  { name: "West Babylon" },
  { name: "Hacienda Heights" },
  { name: "Hickory" },
  { name: "Streamwood" },
  { name: "Norristown" },
  { name: "Fort Pierce" },
  { name: "Lake Worth" },
  { name: "Midland" },
  { name: "Cleveland" },
  { name: "Milford" },
  { name: "Elizabethtown" },
  { name: "Altamonte Springs" },
  { name: "St. Peters" },
  { name: "Kankakee" },
  { name: "North Miami Beach" },
  { name: "Laguna Hills" },
  { name: "Euclid" },
  { name: "The Villages" },
  { name: "Moline" },
  { name: "Newburgh" },
  { name: "Hobbs" },
  { name: "Belvidere" },
  { name: "Carrollton" },
  { name: "San Jacinto" },
  { name: "Whitehall" },
  { name: "Kearny" },
  { name: "Indian Trail" },
  { name: "Randallstown" },
  { name: "Westchester" },
  { name: "Wheeling" },
  { name: "Huntsville" },
  { name: "Jefferson City" },
  { name: "Winston-Salem" },
  { name: "Palm Desert" },
  { name: "Battle Creek" },
  { name: "Palm River-Clair Mel" },
  { name: "Melrose" },
  { name: "Centerville" },
  { name: "Keizer" },
  { name: "North Augusta" },
  { name: "East Honolulu" },
  { name: "Fairfield" },
  { name: "Florissant" },
  { name: "West Bloomfield Township" },
  { name: "Temple" },
  { name: "La Presa" },
  { name: "St. Charles" },
  { name: "West Little River" },
  { name: "DeSoto" },
  { name: "Parkland" },
  { name: "Glen Cove" },
  { name: "Guaynabo" },
  { name: "Oakley" },
  { name: "Tamiami" },
  { name: "Eagle Pass" },
  { name: "North Chicago" },
  { name: "Alton" },
  { name: "Kiryas Joel" },
  { name: "North Royalton" },
  { name: "Mansfield" },
  { name: "West Carson" },
  { name: "Bothell" },
  { name: "Hollister" },
  { name: "Golden Glades" },
  { name: "Garfield" },
  { name: "Montclair" },
  { name: "Lynnwood" },
  { name: "Newnan" },
  { name: "Marietta" },
  { name: "West Hollywood" },
  { name: "South Whittier" },
  { name: "Brentwood" },
  { name: "Burleson" },
  { name: "Aventura" },
  { name: "Martinez" },
  { name: "Richfield" },
  { name: "Rock Island" },
  { name: "Beverly" },
  { name: "Hempstead" },
  { name: "Hallandale Beach" },
  { name: "Stanton" },
  { name: "Cupertino" },
  { name: "Moorpark" },
  { name: "Cleveland" },
  { name: "North Plainfield" },
  { name: "Cumberland" },
  { name: "South Valley" },
  { name: "Clovis" },
  { name: "Fort Lee" },
  { name: "Sanford" },
  { name: "Country Club" },
  { name: "Wilmette" },
  { name: "Leesburg" },
  { name: "Menifee" },
  { name: "Homewood" },
  { name: "Roseville" },
  { name: "Hurst" },
  { name: "La Porte" },
  { name: "Wildomar" },
  { name: "Lompoc" },
  { name: "Burlington" },
  { name: "Dana Point" },
  { name: "East Meadow" },
  { name: "North Attleborough" },
  { name: "Gahanna" },
  { name: "Madison" },
  { name: "Huntley" },
  { name: "Westmont" },
  { name: "Brea" },
  { name: "Carpentersville" },
  { name: "Lufkin" },
  { name: "Oak Creek" },
  { name: "Libertyville" },
  { name: "Altadena" },
  { name: "Monrovia" },
  { name: "Glendale Heights" },
  { name: "North Tustin" },
  { name: "Fair Oaks" },
  { name: "Westfield" },
  { name: "La Verne" },
  { name: "East Cleveland" },
  { name: "Harker Heights" },
  { name: "Five Forks" },
  { name: "Franklin Square" },
  { name: "Fair Lawn" },
  { name: "South Miami Heights" },
  { name: "Fair Oaks" },
  { name: "North Bay Village" },
  { name: "Belton" },
  { name: "London" },
  { name: "Paris" },
  { name: "Rome" },
  { name: "Berlin" },
  { name: "Madrid" },
  { name: "Amsterdam" },
  { name: "Barcelona" },
  { name: "Lisbon" },
  { name: "Vienna" },
  { name: "Prague" },
  { name: "Budapest" },
  { name: "Athens" },
  { name: "Copenhagen" },
  { name: "Stockholm" },
  { name: "Dublin" },
  { name: "Brussels" },
  { name: "Warsaw" },
  { name: "Munich" },
  { name: "Milan" },
  { name: "Venice" },
  { name: "Florence" },
  { name: "Nice" },
  { name: "Lyon" },
  { name: "Porto" },
  { name: "Edinburgh" },
  { name: "Oslo" },
  { name: "Helsinki" },
  { name: "Reykjavik" },
  { name: "Valencia" },
  { name: "Naples" },
  { name: "Zurich" },
  { name: "Geneva" },
  { name: "Krakow" },
  { name: "Seville" },
  { name: "Bilbao" },
  { name: "Bordeaux" },
  { name: "Marseille" },
  { name: "Bratislava" },
  { name: "Ljubljana" },
  { name: "Zagreb" },
  { name: "Tallinn" },
  { name: "Riga" },
  { name: "Vilnius" },
  { name: "Belgrade" },
  { name: "Sofia" },
  { name: "Skopje" },
  { name: "Sarajevo" },
  { name: "Tirana" },
  { name: "Podgorica" },
  { name: "Chisinau" },
  { name: "Luxembourg" },
  { name: "Monaco" },
  { name: "San Marino" },
  { name: "Andorra la Vella" },
  { name: "Valletta" },
  { name: "Basel" },
  { name: "Cologne" },
  { name: "Frankfurt" },
  { name: "Hamburg" },
  { name: "Dusseldorf" },
  { name: "Bologna" },
  { name: "Palermo" },
  { name: "Turin" },
  { name: "Genoa" },
  { name: "Leipzig" },
  { name: "Dresden" },
  { name: "Nuremberg" },
  { name: "Lille" },
  { name: "Ghent" },
  { name: "Antwerp" },
  { name: "The Hague" },
  { name: "Rotterdam" },
  { name: "Utrecht" },
  { name: "Bruges" },
  { name: "Innsbruck" },
  { name: "Salzburg" },
  { name: "Luzern" },
  { name: "Bern" },
  { name: "Thessaloniki" },
  { name: "Patras" },
  { name: "Split" },
  { name: "Dubrovnik" },
  { name: "Constanța" },
  { name: "Cluj-Napoca" },
  { name: "Timișoara" },
  { name: "Lviv" },
  { name: "Kyiv" },
  { name: "Odessa" },
  { name: "St. Petersburg" },
  { name: "Moscow" },
  { name: "Yekaterinburg" },
  { name: "Kaliningrad" },
  { name: "Gdansk" },
  { name: "Wroclaw" },
  { name: "Katowice" },
  { name: "Sheffield" },
  { name: "Bristol" },
  { name: "Manchester" },
  { name: "Birmingham" },
  { name: "Glasgow" },
  { name: "Alicante" },
  { name: "Malaga" },
  { name: "Granada" },
  { name: "Cordoba" },
  { name: "Toledo" },
  { name: "Avila" },
  { name: "Segovia" },
  { name: "San Sebastian" },
  { name: "Pamplona" },
  { name: "La Coruna" },
  { name: "Oviedo" },
  { name: "Badajoz" },
  { name: "Cartagena" },
  { name: "Almeria" },
  { name: "Tarragona" },
  { name: "Gijon" },
  { name: "Valladolid" },
  { name: "Leon" },
  { name: "Huelva" },
  { name: "Burgos" },
  { name: "Treviso" },
  { name: "Verona" },
  { name: "Pisa" },
  { name: "Parma" },
  { name: "Modena" },
  { name: "Perugia" },
  { name: "Rimini" },
  { name: "Bari" },
  { name: "Cagliari" },
  { name: "Messina" },
  { name: "Catania" },
  { name: "Reggio Calabria" },
  { name: "Taranto" },
  { name: "Trapani" },
  { name: "Sassari" },
  { name: "Trieste" },
  { name: "Bolzano" },
  { name: "Inverness" },
  { name: "Aberdeen" },
  { name: "Stirling" },
  { name: "Dundee" },
  { name: "York" },
  { name: "Leeds" },
  { name: "Nottingham" },
  { name: "Cardiff" },
  { name: "Swansea" },
  { name: "Newcastle" },
  { name: "Belfast" },
  { name: "Cork" },
  { name: "Galway" },
  { name: "Limerick" },
  { name: "Waterford" },
  { name: "Århus" },
  { name: "Odense" },
  { name: "Aalborg" },
  { name: "Tampere" },
  { name: "Turku" },
  { name: "Lahti" },
  { name: "Oulu" },
  { name: "Gothenburg" },
  { name: "Malmo" },
  { name: "Uppsala" },
  { name: "Lund" },
  { name: "Bergen" },
  { name: "Trondheim" },
  { name: "Stavanger" },
  { name: "Kristiansand" },
  { name: "Dortmund" },
  { name: "Stuttgart" },
  { name: "Bremen" },
  { name: "Hanover" },
  { name: "Essen" },
  { name: "Mainz" },
  { name: "Mannheim" },
  { name: "Freiburg" },
  { name: "Karlsruhe" },
  { name: "Aachen" },
  { name: "Heidelberg" },
  { name: "Linz" },
  { name: "Graz" },
  { name: "Klagenfurt" },
  { name: "Villach" },
  { name: "Sibiu" },
  { name: "Brasov" },
  { name: "Oradea" },
  { name: "Iasi" },
  { name: "Galati" },
  { name: "Plovdiv" },
  { name: "Varna" },
  { name: "Bansko" },
  { name: "Novi Sad" },
  { name: "Niš" },
  { name: "Subotica" },
  { name: "Debrecen" },
  { name: "Szeged" },
  { name: "Miskolc" },
  { name: "Győr" },
  { name: "Pécs" },
  { name: "Kosice" },
  { name: "Presov" },
  { name: "Nitra" },
  { name: "Trnava" },
  { name: "Martin" },
  { name: "São Paulo" },
  { name: "Buenos Aires" },
  { name: "Rio de Janeiro" },
  { name: "Lima" },
  { name: "Bogotá" },
  { name: "Santiago" },
  { name: "Caracas" },
  { name: "Brasília" },
  { name: "Medellín" },
  { name: "Quito" },
  { name: "Montevideo" },
  { name: "La Paz" },
  { name: "Asunción" },
  { name: "Guayaquil" },
  { name: "Cali" },
  { name: "Recife" },
  { name: "Salvador" },
  { name: "Fortaleza" },
  { name: "Maracaibo" },
  { name: "Barranquilla" },
  { name: "Belo Horizonte" },
  { name: "Córdoba" },
  { name: "Rosario" },
  { name: "Valparaíso" },
  { name: "Santa Cruz de la Sierra" },
  { name: "Arequipa" },
  { name: "Mendoza" },
  { name: "Curitiba" },
  { name: "Porto Alegre" },
  { name: "Florianópolis" },
  { name: "Manaus" },
  { name: "Belém" },
  { name: "João Pessoa" },
  { name: "Maceió" },
  { name: "Campo Grande" },
  { name: "Natal" },
  { name: "San Miguel de Tucumán" },
  { name: "Temuco" },
  { name: "Antofagasta" },
  { name: "Iquique" },
  { name: "Trujillo" },
  { name: "Cusco" },
  { name: "Piura" },
  { name: "Pereira" },
  { name: "Manizales" },
  { name: "Cartagena" },
  { name: "Villavicencio" },
  { name: "Neiva" },
  { name: "Cúcuta" },
  { name: "Arica" },
  { name: "Rancagua" },
  { name: "Copiapó" },
  { name: "Punta Arenas" },
  { name: "Puerto Montt" },
  { name: "Valdivia" },
  { name: "Santa Marta" },
  { name: "Ibague" },
  { name: "Palmira" },
  { name: "Popayán" },
  { name: "Barquisimeto" },
  { name: "Ciudad Guayana" },
  { name: "Maturín" },
  { name: "Puerto La Cruz" },
  { name: "Valencia" },
  { name: "Merida" },
  { name: "San Cristóbal" },
  { name: "Maracay" },
  { name: "Barinas" },
  { name: "Boa Vista" },
  { name: "Porto Velho" },
  { name: "Macapá" },
  { name: "Rio Branco" },
  { name: "São Luís" },
  { name: "Teresina" },
  { name: "Palmas" },
  { name: "Vitória" },
  { name: "Aracaju" },
  { name: "Petrolina" },
  { name: "Santarém" },
  { name: "Uberlândia" },
  { name: "Ribeirão Preto" },
  { name: "Sorocaba" },
  { name: "São José dos Campos" },
  { name: "Caxias do Sul" },
  { name: "Blumenau" },
  { name: "Joinville" },
  { name: "Mar del Plata" },
  { name: "La Plata" },
  { name: "Resistencia" },
  { name: "Bahía Blanca" },
  { name: "Salta" },
  { name: "San Juan" },
  { name: "Corrientes" },
  { name: "Formosa" },
  { name: "Catamarca" },
  { name: "Potosí" },
  { name: "Oruro" },
  { name: "Sucre" },
  { name: "Tarija" },
  { name: "Riberalta" },
  { name: "Cobija" },
  { name: "Sydney" },
  { name: "Melbourne" },
  { name: "Brisbane" },
  { name: "Perth" },
  { name: "Adelaide" },
  { name: "Canberra" },
  { name: "Hobart" },
  { name: "Darwin" },
  { name: "Gold Coast" },
  { name: "Newcastle" },
  { name: "Wollongong" },
  { name: "Geelong" },
  { name: "Townsville" },
  { name: "Cairns" },
  { name: "Toowoomba" },
  { name: "Ballarat" },
  { name: "Bendigo" },
  { name: "Launceston" },
  { name: "Mackay" },
  { name: "Rockhampton" },
  { name: "Bunbury" },
  { name: "Alice Springs" },
  { name: "Bundaberg" },
  { name: "Hervey Bay" },
  { name: "Coffs Harbour" },
  { name: "Wagga Wagga" },
  { name: "Albury" },
  { name: "Kalgoorlie" },
  { name: "Mount Gambier" },
  { name: "Goulburn" },
  { name: "Bathurst" },
  { name: "Dubbo" },
  { name: "Tamworth" },
  { name: "Nowra" },
  { name: "Orange" },
  { name: "Queanbeyan" },
  { name: "Lismore" },
  { name: "Armidale" },
  { name: "Broken Hill" },
  { name: "Katherine" },
  { name: "Broome" },
  { name: "Geraldton" },
  { name: "Esperance" },
  { name: "Port Hedland" },
  { name: "New Plymouth" },
  { name: "Wellington" },
  { name: "Auckland" },
  { name: "Christchurch" },
  { name: "Hamilton" },
  { name: "Dunedin" },
  { name: "Tauranga" },
  { name: "Napier" },
  { name: "Hastings" },
  { name: "Palmerston North" },
  { name: "Nelson" },
  { name: "Rotorua" },
  { name: "Whangarei" },
  { name: "Invercargill" },
  { name: "Timaru" },
  { name: "Gisborne" },
  { name: "Masterton" },
  { name: "Blenheim" },
  { name: "Taupo" },
  { name: "Lower Hutt" },
  { name: "Porirua" },
  { name: "Upper Hutt" },
  { name: "Papakura" },
  { name: "Manukau" },
  { name: "Hobsonville" },
  { name: "Nadi" },
  { name: "Suva" },
  { name: "Lautoka" },
  { name: "Labasa" },
  { name: "Sigatoka" },
  { name: "Apia" },
  { name: "Pago Pago" },
  { name: "Honiara" },
  { name: "Port Moresby" },
  { name: "Lae" },
  { name: "Goroka" },
  { name: "Madang" },
  { name: "Mount Hagen" },
  { name: "Arawa" },
  { name: "Wewak" },
  { name: "Buka" },
  { name: "Funafuti" },
  { name: "Tarawa" },
  { name: "Majuro" },
  { name: "Palikir" },
  { name: "Yaren" },
  { name: "South Tarawa" },
  { name: "Nukunonu" },
  { name: "Avarua" },
  { name: "Nouméa" },
  { name: "Papeete" },
  { name: "Vaitape" },
  { name: "Faaa" },
  { name: "Levuka" },
  { name: "Port Vila" },
  { name: "Luganville" },
  { name: "Antarctica" },
  { name: "Europe" },
  { name: "South America" },
  { name: "Oceania" },
];
